apiVersion: v1
kind: Service
metadata:
  name: morphic-prod-service-clb-morphic
  namespace: morphic-prod
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-type: "classic"
    service.beta.kubernetes.io/aws-load-balancer-backend-protocol: http
    service.beta.kubernetes.io/aws-load-balancer-listener-ports: |
      [
        {"Protocol":"https","Port":"443","InstanceProtocol":"http"}, # HTTPS listener, terminate SSL at LB, forward as HTTP to pods
        {"Protocol":"http","Port":"80","InstanceProtocol":"http"}   # HTTP listener (optional, for redirects or HTTP access)
      ]
    service.beta.kubernetes.io/aws-load-balancer-ssl-cert: arn:aws:acm:eu-west-2:596988661787:certificate/d45ef30e-bf3e-4213-8ca2-1218fe050fc0  # morphic.bio cert
    service.beta.kubernetes.io/aws-load-balancer-ssl-ports: "443"  # SSL ONLY on port 443
spec:
  type: LoadBalancer
  selector:
    app: morphic-website
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 80
    - name: https
      protocol: TCP
      port: 443
      targetPort: 80
