apiVersion: v1
kind: Service
metadata:
  name: gatsby-service
spec:
  selector:
    app: morphic-dev-website
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      name: gatsby-http
    - name: gatsby-https
      protocol: TCP
      port: 443  # HTTPS port
      targetPort: 80
