apiVersion: v1
kind: Service
metadata:
  name: gatsby-service
spec:
  selector:
    app: morphic-dev-website
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
