import React from "react"
import Navbar from "../components/Navbar"
import Footer from "../components/Footer"
import * as styles from "../styles/policies.module.css";
import { Seo } from "../utils/SEO";

export default function Glossary() {
  return (
    <div className={styles.policies}>
      <Navbar />
      <div className={styles.policiesTriangle}></div>

      <section className={styles.policiesContainer}>
        <div className={styles.policiesContentContainer} style={{justifyContent: "flex-start"}}>
          <div className={styles.policiesContent}>

            {/* Main Content */}
            <div className={styles.policiesInfo} style={{ width: "initial" }}>
              <h1 className={styles.titleL}>Glossary</h1>
              <h2>A</h2>
              <p><b>ATAC-seq</b>&nbsp;<i>(Assay for Transposase-Accessible Chromatin using sequencing)</i>: A technique used to map regions of open (accessible) chromatin across the genome. In MorPhiC, ATAC-seq is used to assess how gene knockouts affect chromatin accessibility, providing insight into regulatory changes that follow loss of gene function.</p>
              <hr/>
              <h2>B</h2>
              <p><b>Bulk RNA-seq</b>: A sequencing method that measures the average gene expression across all cells in a sample. MorPhiC uses bulk RNA-seq alongside single-cell methods to profile transcriptional changes resulting from null alleles at population scale.</p>
              <hr/>
              <h2>C</h2>
              <p><b>Catalog (MorPhiC Catalog)</b>: The central deliverable of the MorPhiC program — a publicly available, standardised collection of molecular and cellular phenotypes associated with null alleles for every human protein-coding gene. The catalog is hosted at morphic.bio and is freely accessible to the biomedical community.</p>
              <p><b>Cell Village / KO Village</b>: An experimental strategy in which cells carrying different gene knockouts are pooled and cultured together, then individually identified by sequencing. This multiplexed approach enables high-throughput phenotyping of many gene knockouts simultaneously.</p>
              <p><b>CRISPR</b>: A genome-editing technology (commonly CRISPR-Cas9) used throughout MorPhiC to create null alleles by disrupting specific target genes. Guide RNAs (gRNAs) direct the Cas9 enzyme to cut precise genomic locations, causing loss-of-function mutations.</p>
              <p><b>Community Resource Project</b>: A designation from the National Human Genome Research Institute (NHGRI) indicating that MorPhiC data must be shared openly and promptly with the research community, without restriction, once verified and deposited into public databases.</p>
              <hr/>
              <h2>D</h2>
              <p><b>DAV</b>&nbsp;<i>(Data Analysis and Validation Center)</i>: One of several MorPhiC consortium centres responsible for independently analysing data generated by the DPCs to assess its quality, reproducibility, and utility for diverse biological questions.</p>
              <p><b>DRACC</b>&nbsp;<i>(Data Resource and Administrative Coordinating Center)</i>: The central hub of the MorPhiC consortium responsible for acquiring, standardising, validating, and storing multi-omics data and metadata. The DRACC also maintains the morphic.bio web portal and ensures data are accessible for download, analysis, and visualisation by the broader research community.</p>
              <p><b>DPC</b>&nbsp;<i>(Data Production Research and Development Center)</i>: One of several MorPhiC consortium centres responsible for generating experimental data at scale. DPCs develop and apply diverse cellular systems and assays to produce phenotypic data for gene knockouts.</p>
              <hr/>
              <h2>F</h2>
              <p><b>Functional Genomics</b>: The field of biology focused on understanding the roles of genes and regulatory elements, especially at a genome-wide scale. MorPhiC is a functional genomics initiative aimed at characterising the function of every human protein-coding gene.</p>
              <hr/>
              <h2>G</h2>
              <p><b>Gene Knockout (KO)</b>: The deliberate inactivation of a gene, typically using CRISPR, to create a null allele. MorPhiC systematically creates knockouts across all human protein-coding genes to observe the resulting molecular and cellular phenotypes.</p>
              <p><b>gRNA</b>&nbsp;<i>(Guide RNA)</i>: A short RNA molecule that guides the CRISPR-Cas9 complex to a specific DNA sequence for editing. MorPhiC uses gRNAs to direct knockout of target genes. The gRNA-Enrichment pipeline in MorPhiC tracks and analyses the representation of guide RNAs across experimental samples.</p>
              <hr/>
              <h2>H</h2>
              <p><b>hPSC</b>&nbsp;<i>(Human Pluripotent Stem Cell)</i>: A stem cell type — including both embryonic stem cells (hESCs) and induced pluripotent stem cells (iPSCs) — capable of differentiating into virtually any cell type in the body. MorPhiC uses hPSCs as a standardised, renewable in vitro system for generating null alleles and measuring phenotypes across diverse cell lineages.</p>
              <hr/>
              <h2>I</h2>
              <p><b>iPSC</b>&nbsp;<i>(Induced Pluripotent Stem Cell)</i>: An adult cell that has been reprogrammed back into a pluripotent state. iPSCs are widely used in MorPhiC experiments because they are renewable, genetically tractable, and can be differentiated into many cell types for phenotypic assays.</p>
              <p><b>In Vitro Multicelullar System</b>: A laboratory model in which cells are grown and sometimes differentiated outside a living organism. MorPhiC relies on in vitro multicellular systems — including stem cell-derived organoids and co-cultures — to model gene function in physiologically relevant contexts while enabling systematic, scalable experimentation.</p>
              <hr/>
              <h2>M</h2>
              <p><b>Metadata Scheme</b>: A standardised set of fields and controlled vocabularies used by MorPhiC to describe experimental conditions, cell lines, protocols, and data files. The schema ensures that data produced by different DPCs are interoperable and reproducible.</p>
              <p><b>MorPhiC</b>&nbsp;<i>(Molecular Phenotypes of Null Alleles in Cells)</i>: An NHGRI-funded consortium program launched in 2022 with the goal of cataloguing the molecular and cellular phenotypes of null alleles for every human protein-coding gene using in vitro multicellular systems. The program aims to address a major gap in understanding: the function of the majority of human genes remains unknown or poorly characterised.</p>
              <p><b>Multi-omics</b>: The integration of data from multiple "omics" disciplines — such as genomics, transcriptomics, epigenomics, and proteomics — to build a comprehensive picture of how gene knockouts affect cellular biology. MorPhiC generates and integrates multi-omics datasets for each knocked-out gene.</p>
              <hr/>
              <h2>N</h2>
              <p><b>NHGRI</b>&nbsp;<i>(National Human Genome Research Institute)</i>: The U.S. federal institute that funds and oversees the MorPhiC program. NHGRI's 2020 Strategic Vision called for the biological function of every human gene to be known by 2030 — a goal that MorPhiC directly supports.</p>
              <p><b>Null Allele</b>: A version of a gene that produces no functional protein, typically due to a mutation that disrupts gene expression or creates a non-functional product. Creating null alleles is the primary experimental intervention in MorPhiC, enabling study of what happens to a cell when a given gene is completely absent.</p>
              <hr/>
              <h2>O</h2>
              <p><b>Organoid</b>: A version of a gene that produces no functional protein, typically due to a mutation that disrupts gene expression or creates a non-functional product. Creating null alleles is the primary experimental intervention in MorPhiC, enabling study of what happens to a cell when a given gene is completely absent.</p>
              <hr/>
              <h2>P</h2>
              <p><b>Phenotype (Molecular/Cellular)</b>: The observable characteristics of a cell or organism resulting from its genetic makeup and environment. In MorPhiC, phenotypes are measured at the molecular level (e.g., changes in gene expression, chromatin state) and the cellular level (e.g., changes in cell morphology, proliferation, or differentiation) following gene knockout.</p>
              <p><b>Protein-coding gene</b>: A gene whose DNA sequence is transcribed into RNA and then translated into a protein. The human genome contains approximately 19,000–20,000 protein-coding genes. Systematically characterising all of them is the core mission of MorPhiC.</p>
              <hr/>
              <h2>S</h2>
              <p><b>scRNA-seq</b>&nbsp;<i>(Single-Cell RNA Sequencing)</i>: A sequencing method that measures gene expression in individual cells rather than across a bulk population. MorPhiC uses scRNA-seq to capture cell-to-cell variability in transcriptional responses to gene knockouts, enabling discovery of phenotypes that might be masked in bulk assays.</p>
              <p><b>STAR-suite</b>: A bioinformatics software suite used within MorPhiC for aligning RNA sequencing reads to the human genome. It is a core tool in the consortium's computational pipelines for processing both bulk and single-cell RNA-seq data.</p>
              <hr/>
              <h2>U</h2>
              <p><b>UMI</b>&nbsp;<i>(Unique Molecular Identifier)</i>: A short, random DNA barcode attached to individual molecules before sequencing. UMIs allow MorPhiC researchers to detect and remove PCR duplicates, improving the accuracy of quantification in single-cell and bulk sequencing experiments.</p>
              <hr/>
              <small>This glossary covers key terms used across the MorPhiC program and its associated data, methods, and infrastructure. For full details, refer to the consortium's <a href="https://www.nature.com/articles/s41586-024-08243-w" target="_blank" rel="noopener noreferrer">Nature Perspective (Adli et al., 2025).</a></small>
            </div>
          </div>
        </div>
        <Footer />
      </section>

    </div>
  )
}

export function Head() {
  return <Seo title="MorPhiC program: Molecular Phenotypes of Null Alleles in Cells" />;
}
