name: Deploy to Production

on:
  workflow_dispatch: # This allows the workflow to be triggered manually
    branches:
      - react-app

jobs:
  copy-and-invalidate:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1 # Specify your AWS region

    - name: Copy files from source to destination S3 bucket
      run: |
        aws s3 sync s3://${{ secrets.SOURCE_BUCKET_NAME }} s3://${{ secrets.DESTINATION_BUCKET_NAME }}

    - name: Invalidate CloudFront distribution
      run: |
        aws cloudfront create-invalidation --distribution-id ${{ secrets.CLOUDFRONT_PROD_DISTRIBUTION_ID }} --paths "/*"
